name: Build IPLIST

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cn cidr
      run: |
        chmod +x ros-gen-CN.sh
        ./ros-gen-CN.sh
        
    - name: download google cidr
      run: |
        chmod +x ros-gen-Google.sh
        ./ros-gen-Google.sh

    - name: download telegram cidr
      run: |
        chmod +x ros-gen-TG.sh
        ./ros-gen-TG.sh
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
